export const COUNTRIES: { name: string; code: string; currency: string; currency_name: string; flag: string }[] = [
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', currency_name: 'Afghan Afghani', flag: '🇦🇫' },
  { name: 'Albania', code: 'AL', currency: 'ALL', currency_name: 'Albanian Lek', flag: '🇦🇱' },
  { name: 'Algeria', code: 'DZ', currency: 'DZD', currency_name: 'Algerian Dinar', flag: '🇩🇿' },
  { name: 'Argentina', code: 'AR', currency: 'ARS', currency_name: 'Argentine Peso', flag: '🇦🇷' },
  { name: 'Australia', code: 'AU', currency: 'AUD', currency_name: 'Australian Dollar', flag: '🇦🇺' },
  { name: 'Austria', code: 'AT', currency: 'EUR', currency_name: 'Euro', flag: '🇦🇹' },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', currency_name: 'Bangladeshi Taka', flag: '🇧🇩' },
  { name: 'Belgium', code: 'BE', currency: 'EUR', currency_name: 'Euro', flag: '🇧🇪' },
  { name: 'Brazil', code: 'BR', currency: 'BRL', currency_name: 'Brazilian Real', flag: '🇧🇷' },
  { name: 'Canada', code: 'CA', currency: 'CAD', currency_name: 'Canadian Dollar', flag: '🇨🇦' },
  { name: 'Chile', code: 'CL', currency: 'CLP', currency_name: 'Chilean Peso', flag: '🇨🇱' },
  { name: 'China', code: 'CN', currency: 'CNY', currency_name: 'Chinese Yuan', flag: '🇨🇳' },
  { name: 'Colombia', code: 'CO', currency: 'COP', currency_name: 'Colombian Peso', flag: '🇨🇴' },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK', currency_name: 'Czech Koruna', flag: '🇨🇿' },
  { name: 'Denmark', code: 'DK', currency: 'DKK', currency_name: 'Danish Krone', flag: '🇩🇰' },
  { name: 'Egypt', code: 'EG', currency: 'EGP', currency_name: 'Egyptian Pound', flag: '🇪🇬' },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', currency_name: 'Ethiopian Birr', flag: '🇪🇹' },
  { name: 'Finland', code: 'FI', currency: 'EUR', currency_name: 'Euro', flag: '🇫🇮' },
  { name: 'France', code: 'FR', currency: 'EUR', currency_name: 'Euro', flag: '🇫🇷' },
  { name: 'Germany', code: 'DE', currency: 'EUR', currency_name: 'Euro', flag: '🇩🇪' },
  { name: 'Ghana', code: 'GH', currency: 'GHS', currency_name: 'Ghanaian Cedi', flag: '🇬🇭' },
  { name: 'Greece', code: 'GR', currency: 'EUR', currency_name: 'Euro', flag: '🇬🇷' },
  { name: 'Hong Kong', code: 'HK', currency: 'HKD', currency_name: 'Hong Kong Dollar', flag: '🇭🇰' },
  { name: 'Hungary', code: 'HU', currency: 'HUF', currency_name: 'Hungarian Forint', flag: '🇭🇺' },
  { name: 'India', code: 'IN', currency: 'INR', currency_name: 'Indian Rupee', flag: '🇮🇳' },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', currency_name: 'Indonesian Rupiah', flag: '🇮🇩' },
  { name: 'Iran', code: 'IR', currency: 'IRR', currency_name: 'Iranian Rial', flag: '🇮🇷' },
  { name: 'Iraq', code: 'IQ', currency: 'IQD', currency_name: 'Iraqi Dinar', flag: '🇮🇶' },
  { name: 'Ireland', code: 'IE', currency: 'EUR', currency_name: 'Euro', flag: '🇮🇪' },
  { name: 'Israel', code: 'IL', currency: 'ILS', currency_name: 'Israeli New Shekel', flag: '🇮🇱' },
  { name: 'Italy', code: 'IT', currency: 'EUR', currency_name: 'Euro', flag: '🇮🇹' },
  { name: 'Japan', code: 'JP', currency: 'JPY', currency_name: 'Japanese Yen', flag: '🇯🇵' },
  { name: 'Jordan', code: 'JO', currency: 'JOD', currency_name: 'Jordanian Dinar', flag: '🇯🇴' },
  { name: 'Kenya', code: 'KE', currency: 'KES', currency_name: 'Kenyan Shilling', flag: '🇰🇪' },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', currency_name: 'Malaysian Ringgit', flag: '🇲🇾' },
  { name: 'Mexico', code: 'MX', currency: 'MXN', currency_name: 'Mexican Peso', flag: '🇲🇽' },
  { name: 'Morocco', code: 'MA', currency: 'MAD', currency_name: 'Moroccan Dirham', flag: '🇲🇦' },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', currency_name: 'Euro', flag: '🇳🇱' },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', currency_name: 'New Zealand Dollar', flag: '🇳🇿' },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', currency_name: 'Nigerian Naira', flag: '🇳🇬' },
  { name: 'Norway', code: 'NO', currency: 'NOK', currency_name: 'Norwegian Krone', flag: '🇳🇴' },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', currency_name: 'Pakistani Rupee', flag: '🇵🇰' },
  { name: 'Peru', code: 'PE', currency: 'PEN', currency_name: 'Peruvian Sol', flag: '🇵🇪' },
  { name: 'Philippines', code: 'PH', currency: 'PHP', currency_name: 'Philippine Peso', flag: '🇵🇭' },
  { name: 'Poland', code: 'PL', currency: 'PLN', currency_name: 'Polish Zloty', flag: '🇵🇱' },
  { name: 'Portugal', code: 'PT', currency: 'EUR', currency_name: 'Euro', flag: '🇵🇹' },
  { name: 'Romania', code: 'RO', currency: 'RON', currency_name: 'Romanian Leu', flag: '🇷🇴' },
  { name: 'Russia', code: 'RU', currency: 'RUB', currency_name: 'Russian Ruble', flag: '🇷🇺' },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', currency_name: 'Saudi Riyal', flag: '🇸🇦' },
  { name: 'Singapore', code: 'SG', currency: 'SGD', currency_name: 'Singapore Dollar', flag: '🇸🇬' },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', currency_name: 'South African Rand', flag: '🇿🇦' },
  { name: 'South Korea', code: 'KR', currency: 'KRW', currency_name: 'South Korean Won', flag: '🇰🇷' },
  { name: 'Spain', code: 'ES', currency: 'EUR', currency_name: 'Euro', flag: '🇪🇸' },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', currency_name: 'Sri Lankan Rupee', flag: '🇱🇰' },
  { name: 'Sweden', code: 'SE', currency: 'SEK', currency_name: 'Swedish Krona', flag: '🇸🇪' },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', currency_name: 'Swiss Franc', flag: '🇨🇭' },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', currency_name: 'Taiwan Dollar', flag: '🇹🇼' },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', currency_name: 'Tanzanian Shilling', flag: '🇹🇿' },
  { name: 'Thailand', code: 'TH', currency: 'THB', currency_name: 'Thai Baht', flag: '🇹🇭' },
  { name: 'Turkey', code: 'TR', currency: 'TRY', currency_name: 'Turkish Lira', flag: '🇹🇷' },
  { name: 'Uganda', code: 'UG', currency: 'UGX', currency_name: 'Ugandan Shilling', flag: '🇺🇬' },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', currency_name: 'Ukrainian Hryvnia', flag: '🇺🇦' },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', currency_name: 'UAE Dirham', flag: '🇦🇪' },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', currency_name: 'British Pound', flag: '🇬🇧' },
  { name: 'United States', code: 'US', currency: 'USD', currency_name: 'US Dollar', flag: '🇺🇸' },
  { name: 'Vietnam', code: 'VN', currency: 'VND', currency_name: 'Vietnamese Dong', flag: '🇻🇳' },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', currency_name: 'Zimbabwean Dollar', flag: '🇿🇼' },
];

export const CURRENCIES = [
  'USD', 'EUR', 'GBP', 'JPY', 'CAD', 'AUD', 'CHF', 'CNY', 'INR', 'ZAR',
  'BRL', 'MXN', 'SGD', 'HKD', 'KRW', 'NOK', 'SEK', 'DKK', 'NZD', 'MYR',
  'THB', 'IDR', 'PHP', 'VND', 'TRY', 'RUB', 'AED', 'SAR', 'PKR', 'BDT',
  'EGP', 'NGN', 'KES', 'GHS', 'MAD', 'ILS', 'PLN', 'CZK', 'HUF', 'RON',
  'AFN', 'ALL', 'DZD', 'ARS', 'CLP', 'COP', 'ETB', 'IRR', 'IQD', 'JOD',
  'LKR', 'PEN', 'TWD', 'TZS', 'UAH', 'UGX',
].sort();

export const CATEGORIES = [
  { id: 1, name: 'Food & Dining', icon: '🍽️' },
  { id: 2, name: 'Transport', icon: '🚗' },
  { id: 3, name: 'Accommodation', icon: '🏨' },
  { id: 4, name: 'Office Supplies', icon: '📎' },
  { id: 5, name: 'Entertainment', icon: '🎭' },
  { id: 6, name: 'Healthcare', icon: '🏥' },
  { id: 7, name: 'Training & Education', icon: '📚' },
  { id: 8, name: 'Miscellaneous', icon: '📦' },
];
